import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — SocialAuto by Cloudless',
  description: 'Terms of service for SocialAuto, the social media automation platform by Cloudless.',
  robots: { index: true, follow: true },
}

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16">
      <h1 className="text-3xl font-bold tracking-tight mb-2">Terms of Service</h1>
      <p className="text-muted-foreground mb-8">Last updated: September 17, 2026</p>

      <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 text-sm leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold mb-2">1. The Service</h2>
          <p>
            SocialAuto ("the Service") is a social media automation platform operated by
            Cloudless ("we", "us", "our"), headquartered in Greece, available at
            <a href="https://social.cloudless.gr" className="text-blue-500 hover:underline"> social.cloudless.gr</a>.
            The Service provides AI-assisted content generation, multi-platform publishing,
            scheduling, analytics, and opt-in inbound message auto-replies for your connected
            social media accounts.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">2. Accounts</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>You must provide accurate registration information and keep your credentials secure.</li>
            <li>You must be at least 18 years old or the age of majority in your jurisdiction.</li>
            <li>You are responsible for all activity under your account and team.</li>
            <li>One account per person or business; shared team access is managed via team roles.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">3. Subscriptions and Billing</h2>
          <p>
            Paid plans (Pro, Business, Enterprise) are billed monthly in USD. Payments are
            processed by our Merchant of Record — Polar Software, Inc. (polar.sh) or
            Dodo Payments — which acts as the seller of record, handles payment processing,
            applicable taxes, refunds, and disputes on our behalf.
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Subscriptions renew automatically each billing period until cancelled.</li>
            <li>You can cancel at any time from Settings → Billing or the hosted customer portal; access continues until the end of the paid period.</li>
            <li>Plan quotas (posts, AI calls, connected accounts) are described on the <a href="/pricing" className="text-blue-500 hover:underline">pricing page</a>.</li>
            <li>Failed renewal payments place the subscription in a grace (past-due) state; the plan downgrades to Free if payment is not resolved.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">4. Acceptable Use</h2>
          <p>
            Use of the Service is subject to our
            <a href="/acceptable-use" className="text-blue-500 hover:underline"> Acceptable Use Policy</a>.
            In summary: no spam, no platform manipulation, no unlawful content, and you remain
            responsible for complying with each social network's own terms when publishing or
            automating through SocialAuto.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">5. Automation and Third-Party Platforms</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>Publishing, scheduling, and DM auto-reply features act only on accounts you explicitly connect and configure.</li>
            <li>DM auto-reply is <strong>opt-in, inbound-only</strong>: it answers messages sent to you; it never initiates unsolicited outreach.</li>
            <li>Social platforms may rate-limit, restrict, or suspend accounts for automation. We provide safeguards (rate limits, human-takeover, per-account toggles) but cannot guarantee third-party platform decisions.</li>
            <li>You grant the Service permission to publish content and respond to messages on your behalf, as directed by your configuration.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">6. AI-Generated Content</h2>
          <p>
            Content generated by AI features is provided as a draft for your review. You are
            responsible for reviewing, editing, and approving content before publication and for
            ensuring it complies with applicable law and platform policies.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">7. Intellectual Property</h2>
          <ul className="list-disc pl-6 space-y-1">
            <li>You retain all rights to content you create, upload, or publish through the Service.</li>
            <li>We retain all rights to the Service, its software, and our trademarks.</li>
            <li>You grant us a limited license to store, process, and transmit your content solely to operate the Service.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">8. Termination</h2>
          <p>
            You may delete your account at any time. We may suspend or terminate accounts that
            violate these Terms or the Acceptable Use Policy. Upon termination, your right to use
            the Service ends; data deletion follows our
            <a href="/data-deletion" className="text-blue-500 hover:underline"> Data Deletion Policy</a>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">9. Disclaimers and Limitation of Liability</h2>
          <p>
            The Service is provided "as is" and "as available" without warranties of any kind.
            To the maximum extent permitted by law, Cloudless is not liable for indirect,
            incidental, or consequential damages, nor for actions taken by third-party social
            platforms (including account restrictions or content removal). Our aggregate
            liability is limited to the amounts you paid for the Service in the 12 months
            preceding the claim.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">10. Governing Law</h2>
          <p>
            These Terms are governed by the laws of Greece and the European Union. Disputes are
            subject to the courts of Athens, Greece, unless mandatory consumer-protection law
            provides otherwise.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold mb-2">11. Contact</h2>
          <p>
            Questions about these Terms:
          </p>
          <ul className="list-none pl-6 space-y-1">
            <li>Email: <a href="mailto:support@cloudless.gr" className="text-blue-500 hover:underline">support@cloudless.gr</a></li>
            <li>Website: <a href="https://cloudless.gr" className="text-blue-500 hover:underline">cloudless.gr</a></li>
          </ul>
        </section>
      </div>
    </div>
  )
}
