"""add media collections and r2 storage backend

Revision ID: 9c222774bd04
Revises: d9a5a234d4d7
Create Date: 2026-08-30 22:32:01.262375

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9c222774bd04'
down_revision: str | None = 'd9a5a234d4d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    storage_backend = postgresql.ENUM('local', 'r2', name='storagebackend', create_type=True)
    storage_backend.create(op.get_bind())

    op.create_table(
        'media_collections',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('cover_asset_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_media_collections_team_id_teams'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_media_collections_user_id_users'), ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_media_collections'))
    )
    op.create_index('ix_media_collections_team', 'media_collections', ['team_id'], unique=False)
    op.add_column('media_assets', sa.Column('collection_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('media_assets', sa.Column('storage_backend', sa.Enum('local', 'r2', name='storagebackend'), server_default='local', nullable=False))
    op.add_column('media_assets', sa.Column('public_url', sa.Text(), nullable=True))
    op.add_column('media_assets', sa.Column('ai_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('media_assets', sa.Column('ai_caption', sa.Text(), nullable=True))
    op.add_column('media_assets', sa.Column('embedding_id', sa.String(length=64), nullable=True))
    op.add_column('media_assets', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('media_assets', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('media_assets', sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('media_assets', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('media_assets', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_media_assets_backend', 'media_assets', ['storage_backend'], unique=False)
    op.create_index('ix_media_assets_collection', 'media_assets', ['collection_id'], unique=False)
    op.create_index(op.f('ix_media_assets_embedding_id'), 'media_assets', ['embedding_id'], unique=False)
    op.create_foreign_key(
        op.f('fk_media_assets_collection_id_media_collections'),
        'media_assets', 'media_collections',
        ['collection_id'], ['id'],
        ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_media_assets_collection_id_media_collections'), 'media_assets', type_='foreignkey')
    op.drop_index(op.f('ix_media_assets_embedding_id'), table_name='media_assets')
    op.drop_index('ix_media_assets_collection', table_name='media_assets')
    op.drop_index('ix_media_assets_backend', table_name='media_assets')
    op.drop_column('media_assets', 'updated_at')
    op.drop_column('media_assets', 'meta_data')
    op.drop_column('media_assets', 'usage_count')
    op.drop_column('media_assets', 'is_archived')
    op.drop_column('media_assets', 'is_favorite')
    op.drop_column('media_assets', 'embedding_id')
    op.drop_column('media_assets', 'ai_caption')
    op.drop_column('media_assets', 'ai_tags')
    op.drop_column('media_assets', 'public_url')
    op.drop_column('media_assets', 'storage_backend')
    op.drop_column('media_assets', 'collection_id')
    op.drop_index('ix_media_collections_team', table_name='media_collections')
    op.drop_table('media_collections')
    storage_backend = postgresql.ENUM('local', 'r2', name='storagebackend')
    storage_backend.drop(op.get_bind())
    # ### end Alembic commands ###
