/**
 * Threads social media icon — generated via DMR (Docker Model Runner).
 *
 * The logo was generated by the Cloudless DMR implementation stack using
 * Cloudflare Workers AI (FLUX schnell) — the cloud image-generation fallback
 * in the DMR inference chain (local Diffusers → Cloudflare Workers AI).
 *
 * Media asset ID: 0a82d177-88da-4002-81df-2f35f2679eaf
 * R2 path: 2026/09/09/ee5f6560ee0a4624.png
 *
 * Usage: <ThreadsIcon className="h-5 w-5" />
 */
'use client'

export function ThreadsIcon({ className }: { className?: string }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src="/threads-icon.png"
      alt="Threads"
      className={className}
      style={{ objectFit: 'contain' }}
    />
  )
}
